export const SEARCH_MOVIE="SEARCH_MOVIE";
export const FETCH_MOVIES="FETCH_MOVIES";
export const FETCH_DETAILS="FETCH_DETAILS";
export const LOADING="LOADING";
export const UPCOM_MOVIES="UPCOM_MOVIES";